# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    build: build .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - "8083:3306"

